version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "4567:27017"
    volumes:
      - ./mongo:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/discord-lite
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
    depends_on:
      - mongo
    command: sh -c "npm install && node src/index.js"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    command: npm run dev